name: "sample react ci pipeline /workflow"

on:
   push:
     branches:
       - main
jobs:
   build-and-test:
     runs-on: ubuntu-latest


     steps:
       - name:  "setup node js"
         uses: actions/setup-node@v4
         with:
           node-version: '22'
        
       - name: "code check"
         run: node --version

       - name: "clone repo"
         uses: actions/checkout@v2
       - name: "install dependcery"
         run: npm install

       - name: "list dirctries"
         run: ls -a 